# Generated by Django 4.0.6 on 2023-03-18 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='purchaser_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billApp.coustomersdata'),
        ),
    ]
